apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: cert
  namespace: projectcontour
  annotations:
    fluxcd.io/ignore: "false"
spec:
  secretName: cert
  commonName: "*.devopsnoob.club"
  dnsNames:
  - "*.devopsnoob.club"
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
