apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: podinfo
  namespace: projectcontour
  annotations:
    fluxcd.io/ignore: "false"
spec:
  virtualhost:
    fqdn: podinfo.devopsnoob.club
    tls:
      secretName: cert
  includes:
    - name: podinfo
      namespace: demo
